gd1_legend = {
    '0': "Clear - No coverage",
    '1': "FEW - 2/8 or less",
    '2': "SCATTERED - 3/8-4/8",
    '3': "BROKEN - 5/8-7/8",
    '4': "OVERCAST - 8/8",
    '5': "OBSCURED",
    '6': "PARTIALLY OBSCURED",
    '9': "MISSING"
}

mw1_legend = {
    "00": "Cloud development not observed or not observable",
    "01": "Clouds generally dissolving or becoming less developed",
    "02": "State of sky on the whole unchanged",
    "03": "Clouds generally forming or developing",
    "04": "Visibility reduced by smoke",
    "05": "Haze",
    "06": "Widespread dust in suspension",
    "07": "Dust/sand raised by wind",
    "08": "Well developed dust/sand whirls",
    "09": "Duststorm or sandstorm",
    "10": "Mist",
    "11": "Patches of shallow fog",
    "12": "Continuous shallow fog",
    "13": "Lightning visible, no thunder",
    "14": "Precipitation within sight (not reaching ground)",
    "15": "Precipitation within sight (distant)",
    "16": "Precipitation near but not at station",
    "17": "Thunderstorm, no precipitation",
    "18": "Squalls",
    "19": "Funnel cloud(s)",
    "20": "Drizzle or snow grains (no showers)",
    "21": "Rain (no showers)",
    "22": "Snow (no showers)",
    "23": "Rain and snow or ice pellets (no showers)",
    "24": "Freezing drizzle or rain (no showers)",
    "25": "Showers of rain",
    "26": "Showers of snow or rain and snow",
    "27": "Showers of hail",
    "28": "Fog or ice fog",
    "29": "Thunderstorm",
    "30": "Duststorm/sandstorm decreased",
    "31": "Duststorm/sandstorm no change",
    "32": "Duststorm/sandstorm increased",
    "33": "Severe duststorm/sandstorm decreased",
    "34": "Severe duststorm/sandstorm no change",
    "35": "Severe duststorm/sandstorm increased",
    "36": "Drifting snow (slight/moderate)",
    "37": "Drifting snow (heavy)",
    "38": "Blowing snow (slight/moderate)",
    "39": "Blowing snow (heavy)",
    "40": "Fog/ice fog at distance",
    "41": "Fog/ice fog in patches",
    "42": "Fog/ice fog thinning (sky visible)",
    "43": "Fog/ice fog thinning (sky invisible)",
    "44": "Fog/ice fog steady (sky visible)",
    "45": "Fog/ice fog steady (sky invisible)",
    "46": "Fog/ice fog thickening (sky visible)",
    "47": "Fog/ice fog thickening (sky invisible)",
    "48": "Fog with rime (sky visible)",
    "49": "Fog with rime (sky invisible)",
    "50": "Drizzle (slight, intermittent)",
    "51": "Drizzle (slight, continuous)",
    "52": "Drizzle (moderate, intermittent)",
    "53": "Drizzle (moderate, continuous)",
    "54": "Drizzle (heavy, intermittent)",
    "55": "Drizzle (heavy, continuous)",
    "56": "Freezing drizzle (slight)",
    "57": "Freezing drizzle (moderate/heavy)",
    "58": "Drizzle and rain (slight)",
    "59": "Drizzle and rain (moderate/heavy)",
    "60": "Rain (slight, intermittent)",
    "61": "Rain (slight, continuous)",
    "62": "Rain (moderate, intermittent)",
    "63": "Rain (moderate, continuous)",
    "64": "Rain (heavy, intermittent)",
    "65": "Rain (heavy, continuous)",
    "66": "Freezing rain (slight)",
    "67": "Freezing rain (moderate/heavy)",
    "68": "Rain/drizzle and snow (slight)",
    "69": "Rain/drizzle and snow (moderate/heavy)",
    "70": "Snowflakes (slight, intermittent)",
    "71": "Snowflakes (slight, continuous)",
    "72": "Snowflakes (moderate, intermittent)",
    "73": "Snowflakes (moderate, continuous)",
    "74": "Snowflakes (heavy, intermittent)",
    "75": "Snowflakes (heavy, continuous)",
    "76": "Diamond dust",
    "77": "Snow grains",
    "78": "Star-like snow crystals",
    "79": "Ice pellets",
    "80": "Rain showers (slight)",
    "81": "Rain showers (moderate/heavy)",
    "82": "Rain showers (violent)",
    "83": "Rain/snow mix showers (slight)",
    "84": "Rain/snow mix showers (moderate/heavy)",
    "85": "Snow showers (slight)",
    "86": "Snow showers (moderate/heavy)",
    "87": "Snow pellets/hail showers (slight)",
    "88": "Snow pellets/hail showers (moderate/heavy)",
    "89": "Hail (slight, no thunder)",
    "90": "Hail (moderate/heavy, no thunder)",
    "91": "Rain, past thunderstorm",
    "92": "Rain (moderate/heavy), past thunderstorm",
    "93": "Snow/hail, past thunderstorm",
    "94": "Heavy snow/hail, past thunderstorm",
    "95": "Thunderstorm (slight/moderate, rain/snow)",
    "96": "Thunderstorm (slight/moderate, with hail)",
    "97": "Thunderstorm (heavy, rain/snow)",
    "98": "Thunderstorm with dust/sand storm",
    "99": "Thunderstorm (heavy, with hail)"
}
cloud_8NhCLCMCH_legend = {
    "N": {
        '0': "0 oktas (clear sky)",
        '1': "1 okta",
        '2': "2 oktas",
        '3': "3 oktas",
        '4': "4 oktas",
        '5': "5 oktas",
        '6': "6 oktas",
        '7': "7 oktas",
        '8': "8 oktas (overcast)",
        '9': "Sky obscured or cloud cover not measurable"
    },
    
    "CL": {
        '0': "No CL clouds",
        '1': "Cumulus humilis or cumulus fractus other than of bad weather",
        '2': "Cumulus mediocris or congestus, with or without cumulus fractus or humilis or stratocumulus, all with same base",
        '3': "Cumulonimbus calvus, with or without cumulus, stratocumulus or stratus",
        '4': "Stratocumulus cumulogenitus",
        '5': "Stratocumulus other than stratocumulus cumulogenitus",
        '6': "Stratus nebulosus or stratus fractus other than of bad weather",
        '7': "Stratus fractus or cumulus fractus of bad weather, or both (pannus), below altostratus or nimbostratus",
        '8': "Cumulus and stratocumulus other than stratocumulus cumulogenitus, with different bases",
        '9': "Cumulonimbus capillatus (often with an anvil), with or without other low clouds"
    },

    "CM": {
        '0': "No CM clouds",
        '1': "Altostratus translucidus",
        '2': "Altostratus opacus or nimbostratus",
        '3': "Altocumulus translucidus at a single level",
        '4': "Altocumulus (lenticular), continually changing at one or more levels",
        '5': "Altocumulus in bands/layers, progressively invading sky",
        '6': "Altocumulus cumulogenitus (or cumulonimbogenitus)",
        '7': "Altocumulus translucidus or opacus in multiple or single non-invading layers, or with As/Ns",
        '8': "Altocumulus castellanus or floccus",
        '9': "Altocumulus of a chaotic sky, generally at several levels"
    },

    "CH": {
        '0': "No CH clouds",
        '1': "Cirrus fibratus, sometimes uncinus, not invading sky",
        '2': "Cirrus spissatus in patches or entangled sheaves; may be upper part of Cb or Ci castellanus/floccus",
        '3': "Cirrus spissatus cumulonimbogenitus",
        '4': "Cirrus uncinus or fibratus, or both, progressively invading the sky",
        '5': "Cirrus and cirrostratus in bands or alone, thickening as a whole but veil not reaching 45°",
        '6': "Cirrus and cirrostratus, thickening with veil extending above 45° without total coverage",
        '7': "Cirrostratus covering the whole sky",
        '8': "Cirrostratus not entirely covering the sky",
        '9': "Cirrocumulus alone or predominant among CH clouds"
    }
}

present_weather_legend = {'00': 'Cloud development not observed or not observable', '01': 'Clouds generally dissolving or becoming less developed', '02': 'State of sky on the whole unchanged', '03': 'Clouds generally forming or developing', '04': 'Visibility reduced by smoke, e.g. veldt or forest fires, industrial smoke', '05': 'Haze', '06': 'Widespread dust in suspension in the air', '07': 'Dust or sand raised by wind at the station', '08': 'Well-developed dust/sand whirls', '09': 'Duststorm or sandstorm within sight', '10': 'Mist', '11': 'Patches of shallow fog or ice fog', '12': 'More or less continuous shallow fog or ice fog', '13': 'Lightning visible, no thunder heard', '14': 'Precipitation within sight, not reaching ground', '15': 'Precipitation within sight, reaching ground', '16': 'Precipitation near the station', '17': 'Thunderstorm, no precipitation at observation time', '18': 'Squalls', '19': 'Funnel clouds, tornado, or waterspout', '20': 'Drizzle (not freezing) or snow grains', '21': 'Rain (not freezing)', '22': 'Snow', '23': 'Rain and snow or ice pellets', '24': 'Freezing drizzle or rain', '25': 'Showers of rain', '26': 'Showers of snow or mixed rain and snow', '27': 'Showers of hail', '28': 'Fog or ice fog', '29': 'Thunderstorm', '30': 'Duststorm/sandstorm decreased', '31': 'Slight/moderate duststorm/sandstorm no change', '32': 'Slight/moderate duststorm/sandstorm increased', '33': 'Severe duststorm/sandstorm decreased', '34': 'Severe duststorm/sandstorm no change', '35': 'Severe duststorm/sandstorm increased', '36': 'Slight/moderate drifting snow (low)', '37': 'Heavy drifting snow (low)', '38': 'Slight/moderate blowing snow (high)', '39': 'Heavy blowing snow (high)', '40': 'Fog/ice fog at distance (not at station)', '41': 'Fog/ice fog in patches', '42': 'Fog/ice fog, sky visible, thinning', '43': 'Fog/ice fog, sky invisible, thinning', '44': 'Fog/ice fog, sky visible, no change', '45': 'Fog/ice fog, sky invisible, no change', '46': 'Fog/ice fog, sky visible, thickening', '47': 'Fog/ice fog, sky invisible, thickening', '48': 'Fog with rime, sky visible', '49': 'Fog with rime, sky invisible', '50': 'Drizzle, not freezing, intermittent, slight', '51': 'Drizzle, not freezing, continuous, slight', '52': 'Drizzle, not freezing, intermittent, moderate', '53': 'Drizzle, not freezing, continuous, moderate', '54': 'Drizzle, not freezing, intermittent, heavy', '55': 'Drizzle, not freezing, continuous, heavy', '56': 'Freezing drizzle, slight', '57': 'Freezing drizzle, moderate or heavy', '58': 'Drizzle and rain, slight', '59': 'Drizzle and rain, moderate or heavy', '60': 'Rain, not freezing, intermittent, slight', '61': 'Rain, not freezing, continuous, slight', '62': 'Rain, not freezing, intermittent, moderate', '63': 'Rain, not freezing, continuous, moderate', '64': 'Rain, not freezing, intermittent, heavy', '65': 'Rain, not freezing, continuous, heavy', '66': 'Freezing rain, slight', '67': 'Freezing rain, moderate or heavy', '68': 'Rain/drizzle and snow, slight', '69': 'Rain/drizzle and snow, moderate or heavy', '70': 'Snowflakes, intermittent, slight', '71': 'Snowflakes, continuous, slight', '72': 'Snowflakes, intermittent, moderate', '73': 'Snowflakes, continuous, moderate', '74': 'Snowflakes, intermittent, heavy', '75': 'Snowflakes, continuous, heavy', '76': 'Diamond dust', '77': 'Snow grains', '78': 'Star-like snow crystals', '79': 'Ice pellets', '80': 'Rain showers, slight', '81': 'Rain showers, moderate or heavy', '82': 'Rain showers, violent', '83': 'Rain and snow mix showers, slight', '84': 'Rain and snow mix showers, moderate or heavy', '85': 'Snow showers, slight', '86': 'Snow showers, moderate or heavy', '87': 'Showers of snow pellets/hail, slight', '88': 'Showers of snow pellets/hail, moderate or heavy', '89': 'Hail, slight, no thunder', '90': 'Hail, moderate/heavy, no thunder', '91': 'Rain after thunderstorm', '92': 'Rain, moderate/heavy, after thunderstorm', '93': 'Snow/hail, after thunderstorm', '94': 'Heavy snow/hail, after thunderstorm', '95': 'Thunderstorm, slight/moderate, with rain/snow', '96': 'Thunderstorm, slight/moderate, with hail', '97': 'Thunderstorm, heavy, with rain/snow', '98': 'Thunderstorm with dust/sand storm', '99': 'Thunderstorm, heavy, with hail'}

past_weather_legend = {'0': 'Cloud covering 1/2 or less of the sky throughout the period', '1': 'Cloud covering >1/2 during part of the period', '2': 'Cloud covering >1/2 of the sky throughout the period', '3': 'Sandstorm, duststorm, or blowing snow', '4': 'Fog or ice fog or thick haze', '5': 'Drizzle', '6': 'Rain', '7': 'Snow, or rain and snow mixed', '8': 'Shower(s)', '9': 'Thunderstorm(s) with or without precipitation'}

cloud_amount_legend = {
    '0': "0 oktas",
    '1': "1/8 or less",
    '2': "2/8",
    '3': "3/8",
    '4': "4/8",
    '5': "5/8",
    '6': "6/8",
    '7': "7/8 or more, but not 8/8",
    '8': "8/8 (overcast)",
    '9': "Sky obscured or cannot be estimated",
    '/': "No measurement made"
}

cloud_type_legend = {
    '0': "Cirrus (Ci)",
    '1': "Cirrocumulus (Cc)",
    '2': "Cirrostratus (Cs)",
    '3': "Altocumulus (Ac)",
    '4': "Altostratus (As)",
    '5': "Nimbostratus (Ns)",
    '6': "Stratocumulus (Sc)",
    '7': "Stratus (St)",
    '8': "Cumulus (Cu)",
    '9': "Cumulonimbus (Cb)",
    '/': "Cloud not visible (darkness, fog, etc.)"
}

cloud_height_legend = {
    '00': "<100 ft", '01': "100–200 ft", '02': "200–300 ft", '03': "300–400 ft", '04': "400–500 ft",
    '05': "500–600 ft", '06': "600–700 ft", '07': "700–800 ft", '08': "800–900 ft", '09': "900–1000 ft",
    '10': "1000–1100 ft", '11': "1100–1200 ft", '12': "1200–1300 ft", '13': "1300–1400 ft", '14': "1400–1500 ft",
    '15': "1500–1600 ft", '16': "1600–1700 ft", '17': "1700–1800 ft", '18': "1800–1900 ft", '19': "1900–2000 ft",
    '20': "2000–2100 ft", '21': "2100–2200 ft", '22': "2200–2300 ft", '23': "2300–2400 ft", '24': "2400–2500 ft",
    '25': "2500–2600 ft", '26': "2600–2700 ft", '27': "2700–2800 ft", '28': "2800–2900 ft", '29': "2900–3000 ft",
    '30': "3000–3100 ft", '31': "3100–3200 ft", '32': "3200–3300 ft", '33': "3300–3400 ft",
    '34': "3400–3500 ft", '35': "3500–3600 ft", '36': "3600–3700 ft", '37': "3700–3800 ft", '38': "3800–3900 ft",
    '39': "3900–4000 ft", '40': "4000–4100 ft", '41': "4100–4200 ft", '42': "4200–4300 ft", '43': "4300–4400 ft",
    '44': "4400–4500 ft", '45': "4500–4600 ft", '46': "4600–4700 ft", '47': "4700–4800 ft", '48': "4800–4900 ft",
    '49': "4900–5000 ft", '50': "5000–5100 ft", '51': "5100–5200 ft", '52': "5200–5300 ft", '53': "5300–5400 ft",
    '54': "5400–5500 ft", '55': "5500–5600 ft", '56': "6000 ft", '57': "7000 ft", '58': "8000 ft", '59': "9000 ft",
    '60': "10000 ft", '61': "11000 ft", '62': "12000 ft", '63': "13000 ft", '64': "14000 ft", '65': "15000 ft",
    '66': "16000 ft", '67': "17000 ft", '68': "18000 ft", '69': "19000 ft", '70': "20000 ft", '71': "21000 ft",
    '72': "22000 ft", '73': "23000 ft", '74': "24000 ft", '75': "25000 ft", '76': "26000 ft", '77': "27000 ft",
    '78': "28000 ft", '79': "29000 ft", '80': "30000 ft", '81': "31000 ft", '82': "32000 ft", '83': "33000 ft",
    '84': "34000 ft", '85': "35000 ft", '86': "36000 ft", '87': "37000 ft", '88': "38000 ft", '89': "<38000 ft",
    '90': "<50 ft", '91': "50–100 ft", '92': "100–200 ft", '93': "200–300 ft", '94': "300–600 ft",
    '95': "600–1000 ft", '96': "1000–1500 ft", '97': "1500–2000 ft", '98': "2000–2500 ft", '99': ">2500 ft"
}
